name: Lua Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"
    
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install luacheck
      run: luarocks install luacheck
    
    - name: Run luacheck
      run: |
        luacheck . --formatter JUnit > lint-results.xml || true
        luacheck . || true
    
    - name: Annotate files
      uses: yuzutech/annotations-action@v0.5.0
      if: always()
      with:
        reports: lint-results.xml
        title: Lua Linting Results
    
    - name: Generate summary
      if: always()
      run: |
        echo "## Lua Linting Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        luacheck . --formatter default || true >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY